name: geo_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - imageio
  - numpy
  - pandas
  - matplotlib
  - geopandas
  - xarray
  - tqdm
  - cartopy
  - netcdf4
  - pydap
  - gdal
  - libgdal
  - fiona
  - ffmpeg
  - dask
  - bottleneck
